services:
  postgres:
    container_name: postgres_container
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${PG_NAME}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    networks:
      - postgres
    ports:
      - 5432:5432

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
